### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by soham98** [HappyHobby/HappyHobby#66]
**Description of the issue:**
The images present in your settings page don't have an aria-label or alt text 

**Reproduction of steps:**
N/A

**Rationale:**
As you know aria labels and alt text is very important to allow frictionless usage of your application by users who have disabilities. Your main "Daily Hobby" page has these labels but when you are going into settings to set your choices, those images do not have them

**Comment by thejameskim** [comment]
Thank you for your issue. Alt-tags are important for users who have disabilities to use our application and we will get a quick fix in. However, I'm downgrading this to a minor bug because functionality can still be used to accomplish the intended task using the workaround of aria-labels present on the buttons. This does not qualify as a major bug because images not having aria-labels do not prevent the screen reader from using our application.
