### ISSUE TITLE
Minor: making the interests page more visible

### ISSUE THREAD

**Issue by pranita122** [HappyHobby/HappyHobby#70]
It might be better to include a separate tab on the menu bar for the user to edit interests so it's not so hidden. It seems like a key feature on this app, so it should be easily accessible.

**Comment by thejameskim** [comment]
Thanks for the feedback! As this doesn't break functionality and is an enhancement to our application, I'll mark it as such. Also, we will not be able to provide this enhancement in this release because it is out of scope from our requirements and would require creating more components to satisfy this enhancement.
