### ISSUE TITLE
Minor: make the page for intuitive and easier to navigate

### ISSUE THREAD

**Issue by edwardhalimm** [HappyHobby/HappyHobby#71]
When use get the random activity/ hobby. I think it'd be beneficial to put youtube video suggestions or article suggestion that explaining about the hobby. It also helpful if there's a "Random" button user can press to get different results.

**Comment by thejameskim** [comment]
Thanks for the feedback! As this doesn't break functionality and is an enhancement to our application, I'll mark it as such. Also, we will not be able to provide this enhancement in this release because it is out of scope from our requirements and would require creating more components to satisfy this enhancement.
